import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ToastProvider from "@/provider/ToastProvider";
import { SessionProvider } from "next-auth/react";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Next Car",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${lato.className} antialiased min-h-screen w-full`}>
          <ToastProvider></ToastProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </body>
      </SessionProvider>
    </html>
  );
}
